// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorApp.Migrations
{
    [DbContext(typeof(BlazorUsersDbContext))]
    [Migration("20201221063213_Initial-Commit")]
    partial class InitialCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("BlazorApp.Data.BlazorUser", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone_Number")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("BlazorUser");

                    b.HasData(
                        new
                        {
                            Name = "NewUser",
                            Domain = "gmail.com",
                            Email = "NewUser@gmail.com",
                            Notes = " first blazor app",
                            Phone_Number = "0711111111"
                        },
                        new
                        {
                            Name = "NewUser2",
                            Domain = "gmail.com",
                            Email = "NewUser2@gmail.com",
                            Notes = " first blazor app",
                            Phone_Number = "0711111112"
                        },
                        new
                        {
                            Name = "NewUser3",
                            Domain = "gmail.com",
                            Email = "NewUser3@gmail.com",
                            Notes = " first blazor app",
                            Phone_Number = "0711111113"
                        },
                        new
                        {
                            Name = "NewUser4",
                            Domain = "gmail.com",
                            Email = "NewUser4@gmail.com",
                            Notes = " first blazor app",
                            Phone_Number = "0711111114"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
